# Generated by Django 4.0 on 2021-12-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='project/')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
